spring.application.name=demo.FieldOps
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/fieldops
spring.datasource.username=root
spring.datasource.password=root1234

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
//spring.jpa.show-sql.format = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Mail Notification
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vinoothnamukkamala@gmail.com
spring.mail.password=gxqx bbzu dgzt oncx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false

#Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Server Port (optional)
server.port=8070